/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.almondmendoza.talkingCaller;

public final class R {
    public static final class array {
        public static final int language_entries=0x7f040000;
        public static final int language_values=0x7f040002;
        public static final int speech_language_values=0x7f040001;
        /**  Speed settings 
 Speed settings 
 Speed settings 
         */
        public static final int speed_entries=0x7f040003;
        public static final int speed_entryvalues=0x7f040004;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int help48=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int settings48=0x7f020002;
    }
    public static final class id {
        public static final int backInstructionBtn=0x7f060003;
        public static final int callBtn=0x7f060000;
        public static final int cancelCallBtn=0x7f060001;
        public static final int languageBtn=0x7f060004;
        public static final int languageCancelBtn=0x7f060006;
        public static final int languageNextBtn=0x7f060005;
        public static final int psNoBtn=0x7f060009;
        public static final int psYesBtn=0x7f060008;
        public static final int selection=0x7f060007;
        public static final int speedCancelBtn=0x7f06000d;
        public static final int speedDownBtn=0x7f06000b;
        public static final int speedOkBtn=0x7f06000c;
        public static final int speedUpBtn=0x7f06000a;
        public static final int txtInstruction=0x7f060002;
    }
    public static final class layout {
        public static final int call_confirm=0x7f030000;
        public static final int instruction=0x7f030001;
        public static final int language_selection=0x7f030002;
        public static final int main=0x7f030003;
        public static final int normal_preferences=0x7f030004;
        public static final int preferences_selection=0x7f030005;
        public static final int speed_preferences=0x7f030006;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int back=0x7f050006;
        public static final int back_to_your_contact_list=0x7f05001b;
        public static final int call=0x7f050005;
        public static final int call_cancel=0x7f050013;
        public static final int call_ended=0x7f05002a;
        public static final int call_start=0x7f050012;
        public static final int cancel=0x7f050004;
        public static final int cancel_preferences=0x7f050010;
        public static final int fastest_testing_phrase=0x7f050018;
        public static final int incoming_call_ended=0x7f05002b;
        public static final int incoming_ringing=0x7f05002c;
        public static final int instructions=0x7f050002;
        public static final int instructions_speech=0x7f050019;
        public static final int instructions_speech_text=0x7f05001a;
        public static final int next=0x7f050009;
        public static final int no=0x7f050008;
        public static final int normal_preferences_default_language=0x7f05001f;
        public static final int normal_preferences_default_language_words=0x7f050022;
        public static final int normal_preferences_default_speech_rate=0x7f050020;
        public static final int normal_preferences_preview=0x7f050021;
        public static final int ok=0x7f050003;
        public static final int open_preferences=0x7f05001c;
        public static final int preferences_language_open_speech=0x7f050029;
        public static final int preferences_read_sms=0x7f050026;
        public static final int preferences_read_sms_desc_off=0x7f050028;
        public static final int preferences_read_sms_desc_on=0x7f050027;
        public static final int preferences_talking_caller_id=0x7f050023;
        public static final int preferences_talking_caller_id_des_off=0x7f050025;
        public static final int preferences_talking_caller_id_des_on=0x7f050024;
        public static final int received_new_sms=0x7f05002d;
        public static final int saved_preferences=0x7f05000f;
        public static final int sequence_length_pref=0x7f050030;
        public static final int settings=0x7f050001;
        public static final int slowest_testing_phrase=0x7f050017;
        public static final int speed_down=0x7f05000b;
        public static final int speed_setting_saved=0x7f05001e;
        public static final int speed_setting_special=0x7f05001d;
        public static final int speed_settings=0x7f05000e;
        public static final int speed_settings_cancel=0x7f050031;
        public static final int speed_up=0x7f05000a;
        public static final int tap_to_call=0x7f050011;
        public static final int testing_phrase=0x7f050014;
        public static final int testing_phrase_en_us=0x7f05002e;
        public static final int testing_phrase_tl=0x7f05002f;
        public static final int testing_speed_down_phrase=0x7f050016;
        public static final int testing_speed_up_phrase=0x7f050015;
        public static final int welcome_note=0x7f05000c;
        public static final int welcome_note_with_instruction=0x7f05000d;
        public static final int yes=0x7f050007;
    }
}
